
import java.awt.Color;
import static java.awt.SystemColor.window;
import java.awt.event.ActionEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.BadLocationException;
import javax.swing.text.Highlighter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author mocmeo
 */
public class FindDialog extends javax.swing.JFrame {

    protected MainWindow window;
    protected JTextArea textArea;
    protected Highlighter highlighter;
    protected Highlighter.HighlightPainter painter;
    private Color entryBg;
    private String ret_keyword;

    private int findPosn = 0;
    private boolean backward = false;
    private boolean findCase = false;

    public FindDialog(MainWindow win) {
        initComponents();
        buttonGroup1.add(upDirection);
        buttonGroup1.add(downDirection);

        this.window = win;
        textArea = window.getTextArea();
        highlighter = window.getHighlighter();
        painter = window.getPainter();

        entryBg = keywordField.getBackground();
        downDirection.setSelected(true);

        // dispose the frame instead of exiting
        // without this, application will be terminated
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        findNextButton.setEnabled(false);
        this.setTitle("Find");
        window.setFindNext(false);
        
    }

    private FindDialog() {
        initComponents();
    }

    public JTextField getKeywordField() {
        return keywordField;
    }

    public int getFindPosn() {
        return findPosn;
    }

    public String getKeyword() {
        return ret_keyword;
    }

    public boolean getFindCase() {
        return findCase;
    }

    public boolean getBackWard() {
        return backward;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        findLabel = new javax.swing.JLabel();
        keywordField = new javax.swing.JTextField();
        findNextButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        matchCaseBox = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        upDirection = new javax.swing.JRadioButton();
        downDirection = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        findLabel.setText("Find what:");

        keywordField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                keywordFieldCaretUpdate(evt);
            }
        });
        keywordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keywordFieldActionPerformed(evt);
            }
        });

        findNextButton.setText("Find Next");
        findNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findNextButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        matchCaseBox.setText("Match case");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Direction"));

        upDirection.setText("Up");

        downDirection.setText("Down");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(upDirection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(downDirection)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upDirection)
                    .addComponent(downDirection))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(findLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(keywordField, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(matchCaseBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(findNextButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(findNextButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(findLabel)
                            .addComponent(keywordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(matchCaseBox)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        highlighter.removeAllHighlights();
//        keywordField.setText("");
        if (keywordField.getText().isEmpty()) {
            window.setFindNext(false);
        }
        window.setHighlightTag(null);
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    @Override
    public void dispose() {
        highlighter.removeAllHighlights();
        if (keywordField.getText().isEmpty()) {
            window.setFindNext(false);
        }
        super.dispose();
    }
    private void findNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findNextButtonActionPerformed
        findPosn = textArea.getCaretPosition();
        highlighter.removeAllHighlights();

        String keyword = keywordField.getText();
        if (keyword.isEmpty()) {
            return;
        }
        
        window.setFindNext(true);
        String content = textArea.getText();
        int index = content.indexOf(keyword, findPosn);
        if (matchCaseBox.isSelected()) {
            index = content.toLowerCase().indexOf(keyword.toLowerCase(), findPosn);
        }

        if (upDirection.isSelected()) {
            index = content.lastIndexOf(keyword, findPosn - 1);
            if (matchCaseBox.isSelected()) {
                index = content.toLowerCase().lastIndexOf(keyword.toLowerCase(), findPosn - 1);
            }
        }

        if (index >= 0) {   // match found
            try {
                int end = index + keyword.length();
                findPosn = end;
                window.setHighlightTag(highlighter.addHighlight(index, end, painter));

                textArea.setCaretPosition(end);
                if (upDirection.isSelected()) {
                    textArea.setCaretPosition(index);
                }
                keywordField.setBackground(entryBg);
            } catch (BadLocationException e) {
            }
        } else {
            window.setHighlightTag(null);
            keywordField.setBackground(Color.LIGHT_GRAY);
            JOptionPane.showMessageDialog(this, "Cannot find \"" + keyword + "\"",
                    "Notepad", JOptionPane.INFORMATION_MESSAGE);
        }
        findCase = matchCaseBox.isSelected();
        backward = upDirection.isSelected();
        ret_keyword = keywordField.getText();
    }//GEN-LAST:event_findNextButtonActionPerformed

    private void keywordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keywordFieldActionPerformed
        findNextButtonActionPerformed(evt);
    }//GEN-LAST:event_keywordFieldActionPerformed

    private void keywordFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_keywordFieldCaretUpdate
        if (keywordField.getText().isEmpty()) {
            findNextButton.setEnabled(false);
        } else {
            findNextButton.setEnabled(true);
        }
    }//GEN-LAST:event_keywordFieldCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton downDirection;
    private javax.swing.JLabel findLabel;
    private javax.swing.JButton findNextButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField keywordField;
    private javax.swing.JCheckBox matchCaseBox;
    private javax.swing.JRadioButton upDirection;
    // End of variables declaration//GEN-END:variables
}
